import json
import requests

def generate_tactical_report(json_filepath="tactical_stats.json"):
    try:
        with open(json_filepath, 'r') as f:
            tactical_stats = json.load(f)
    except FileNotFoundError:
        return "Error: tactical_stats.json not found. Please run main.py first to generate the data."
        
    prompt = f"""
You are an expert football tactician and scout. Analyze this match data: 
{json.dumps(tactical_stats, indent=2)}

Identify which players are dominating possession, the overall team pace, and suggest three specific tactical counter-strategies to defeat Team 1.
Keep your response concise, structured, and easy to read for coaches.
"""

    url = "http://localhost:11434/api/generate"
    payload = {
        "model": "llama3.2:3b",
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(url, json=payload, timeout=120)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "No response generated by the model.")
    except Exception as e:
        return f"Error communicating with local LLM (Ollama): {str(e)}"

if __name__ == "__main__":
    report = generate_tactical_report()
    print("=== TACTICAL SCOUTING REPORT ===")
    print(report)
